# Site settings
title: Income Share Agreements
tag_text: Income Share Agreements
description: An essay on the next era of personal finance
url: "https://vigilant-morse-ba89ce.netlify.com/"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
